//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulezzClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInfo
    {
        public int Id { get; set; }
        public int Count { get; set; }
        public decimal PurchasePrice { get; set; }
        public int IdPurchaseReport { get; set; }
        public int IdProduct { get; set; }
        public int IdExchangeRate { get; set; }
    
        public virtual ExchangeRate ExchangeRate { get; set; }
        public virtual Product Product { get; set; }
        public virtual PurchaseReport PurchaseReport { get; set; }
    }
}
