USE Store
GO

CREATE TRIGGER Groups_INSERT
ON Groups
AFTER INSERT
AS
INSERT INTO Stores(Title) SELECT Title FROM INSERTED WHERE IdParentGroup IS NULL
GO

CREATE TRIGGER Groups_UPDATE
ON Groups
AFTER UPDATE
AS
UPDATE Stores Set Title = (SELECT Title FROM INSERTED WHERE IdParentGroup IS NULL) WHERE Title = (SELECT Title FROM deleted WHERE IdParentGroup IS NULL)
GO

CREATE TRIGGER Groups_DELETE
ON Groups
AFTER DELETE
AS
DELETE Stores WHERE Title = (SELECT Title FROM deleted WHERE IdParentGroup IS NULL)
GO 