//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelModul
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counterparties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Counterparties()
        {
            this.MoneyTransfers = new HashSet<MoneyTransfers>();
            this.MovementGoodsReports = new HashSet<MovementGoodsReports>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string Props { get; set; }
        public string Address { get; set; }
        public int WhoIsIt { get; set; }
        public decimal Debt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyTransfers> MoneyTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementGoodsReports> MovementGoodsReports { get; set; }
    }
}
