//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelModul
{
    public partial class CountProducts
    {
        public int IdProduct { get; set; }
        public int IdStore { get; set; }
        public double Count { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
