//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelModul
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTransfers
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int IdCounterparty { get; set; }
        public decimal MoneyAmount { get; set; }
        public int TypeTransfer { get; set; }
    
        public virtual Counterparties Counterparties { get; set; }
    }
}
