//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelModul
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementGoodsInfos
    {
        public int Id { get; set; }
        public int Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int IdReport { get; set; }
        public int IdProduct { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual MovementGoodsReports MovementGoodsReports { get; set; }
    }
}
