//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelModul
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementGoodsReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovementGoodsReports()
        {
            this.MovementGoodsInfos = new HashSet<MovementGoodsInfos>();
            this.MovementGoodsReports1 = new HashSet<MovementGoodsReports>();
            this.SerialNumbers = new HashSet<SerialNumbers>();
            this.SerialNumbers1 = new HashSet<SerialNumbers>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Course { get; set; }
        public string TextInfo { get; set; }
        public Nullable<int> IdArrivalStore { get; set; }
        public Nullable<int> IdDisposalStore { get; set; }
        public Nullable<int> IdCounterparty { get; set; }
        public Nullable<int> IdExchangeRate { get; set; }
        public int TypeAction { get; set; }
        public Nullable<int> IdMovementGoodsReport { get; set; }
    
        public virtual Counterparties Counterparties { get; set; }
        public virtual ExchangeRates ExchangeRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementGoodsInfos> MovementGoodsInfos { get; set; }
        public virtual Stores Stores { get; set; }
        public virtual Stores Stores1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementGoodsReports> MovementGoodsReports1 { get; set; }
        public virtual MovementGoodsReports MovementGoodsReports2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumbers> SerialNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumbers> SerialNumbers1 { get; set; }
    }
}
