//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelModul
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.CountProducts = new HashSet<CountProducts>();
            this.PropertyProducts = new HashSet<PropertyProducts>();
            this.PurchaseInfos = new HashSet<PurchaseInfos>();
            this.RevaluationProductsInfos = new HashSet<RevaluationProductsInfos>();
            this.SalesInfos = new HashSet<SalesInfos>();
            this.SerialNumbers = new HashSet<SerialNumbers>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string VendorCode { get; set; }
        public string Barcode { get; set; }
        public decimal SalesPrice { get; set; }
        public int IdWarrantyPeriod { get; set; }
        public int IdGroup { get; set; }
        public int IdUnitStorage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountProducts> CountProducts { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual UnitStorages UnitStorages { get; set; }
        public virtual WarrantyPeriods WarrantyPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyProducts> PropertyProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInfos> PurchaseInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevaluationProductsInfos> RevaluationProductsInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInfos> SalesInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumbers> SerialNumbers { get; set; }
    }
}
