//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace ModelModul
{
    public partial class Products
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            CountProducts = new HashSet<CountProducts>();
            PropertyProducts = new HashSet<PropertyProducts>();
            PurchaseInfos = new HashSet<PurchaseInfos>();
            RevaluationProductsInfos = new HashSet<RevaluationProductsInfos>();
            SalesInfos = new HashSet<SalesInfos>();
            SerialNumbers = new HashSet<SerialNumbers>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string VendorCode { get; set; }
        public string Barcode { get; set; }
        public decimal SalesPrice { get; set; }
        public int IdWarrantyPeriod { get; set; }
        public int IdGroup { get; set; }
        public int IdUnitStorage { get; set; }
    
        public virtual Groups Groups { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountProducts> CountProducts { get; set; }
        public virtual UnitStorages UnitStorages { get; set; }
        public virtual WarrantyPeriods WarrantyPeriods { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyProducts> PropertyProducts { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInfos> PurchaseInfos { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevaluationProductsInfos> RevaluationProductsInfos { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInfos> SalesInfos { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumbers> SerialNumbers { get; set; }
    }
}
