//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace ModelModul
{
    public partial class PurchaseReports
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseReports()
        {
            this.PurchaseInfos = new HashSet<PurchaseInfos>();
        }
    
        public int Id { get; set; }
        public DateTime DataOrder { get; set; }
        public int IdStore { get; set; }
        public int IdSupplier { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInfos> PurchaseInfos { get; set; }
        public virtual Stores Stores { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
