//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelModul
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInfos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseInfos()
        {
            this.SerialNumbers = new HashSet<SerialNumbers>();
        }
    
        public int Id { get; set; }
        public int Count { get; set; }
        public decimal PurchasePrice { get; set; }
        public int IdPurchaseReport { get; set; }
        public int IdProduct { get; set; }
        public int IdExchangeRate { get; set; }
    
        public virtual ExchangeRates ExchangeRates { get; set; }
        public virtual Products Products { get; set; }
        public virtual PurchaseReports PurchaseReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumbers> SerialNumbers { get; set; }
    }
}
