//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ModelModul
{
    public partial class RevaluationProducts
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public DateTime Date { get; set; }
        public decimal OldSalesPrice { get; set; }
        public decimal NewSalesPrice { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
