//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace ModelModul
{
    public partial class SerialNumbers
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SerialNumbers()
        {
            this.SalesInfos = new HashSet<SalesInfos>();
            this.Warranties = new HashSet<Warranties>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<DateTime> SelleDate { get; set; }
        public DateTime PurchaseDate { get; set; }
        public int IdProduct { get; set; }
        public int IdSupplier { get; set; }
    
        public virtual Products Products { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInfos> SalesInfos { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warranties> Warranties { get; set; }
    }
}
