//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ModelModul
{
    public partial class StoreEntities : DbContext
    {
        public StoreEntities()
            : base("name=StoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExchangeRates> ExchangeRates { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<PriceGroups> PriceGroups { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<PropertyNames> PropertyNames { get; set; }
        public virtual DbSet<PropertyProducts> PropertyProducts { get; set; }
        public virtual DbSet<PropertyValues> PropertyValues { get; set; }
        public virtual DbSet<PurchaseInfos> PurchaseInfos { get; set; }
        public virtual DbSet<PurchaseReports> PurchaseReports { get; set; }
        public virtual DbSet<RevaluationProducts> RevaluationProducts { get; set; }
        public virtual DbSet<SalesInfos> SalesInfos { get; set; }
        public virtual DbSet<SalesReports> SalesReports { get; set; }
        public virtual DbSet<SerialNumbers> SerialNumbers { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<UnitStorages> UnitStorages { get; set; }
        public virtual DbSet<Warranties> Warranties { get; set; }
        public virtual DbSet<WarrantyPeriods> WarrantyPeriods { get; set; }
        public virtual DbSet<CountProducts> CountProducts { get; set; }
    }
}
