//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ModelModul
{
    public class Warranties
    {
        public int Id { get; set; }
        public string Malfunction { get; set; }
        public DateTime? DateReceipt { get; set; }
        public DateTime? DateDeparture { get; set; }
        public DateTime? DateIssue { get; set; }
        public string Info { get; set; }
        public int IdSerialNumber { get; set; }
    
        public virtual SerialNumbers SerialNumbers { get; set; }
    }
}
